Don't transform filter() unless it has a return statement
A developer can accidentally, for example, forget the `return` keyword,
which causes the predicate to have one expression statement. That
predicate returns `undefined` so we should not attempt to transform it
into a ChiselStrike __filterWithExpression().

Fixes the following panic:

  thread 'main' panicked at 'not yet implemented', chiselc/src/transforms/filter.rs:59:21

Spotted by Jan Plhak.