tests/common: Add run_in() variant
This adds a run_in() variant where we can specify another directory to
run in.

Please note that for some reason this change confuses the hell out of
linters:

error: function is never used: `run`
  --> cli/tests/common/mod.rs:14:8
   |
14 | pub fn run<T: IntoIterator<Item = &'static str>>(cmd: &str, args: T) {
   |        ^^^
   |
   = note: `-D dead-code` implied by `-D warnings`

error: function is never used: `bin_dir`
  --> cli/tests/common/mod.rs:18:8
use std::env;
   |
18 | pub fn bin_dir() -> PathBuf {
   |        ^^^^^^^

error: function is never used: `repo_dir`
  --> cli/tests/common/mod.rs:25:8
   |
25 | pub fn repo_dir() -> PathBuf {
   |        ^^^^^^^^

error: could not compile `cli` due to 3 previous errors

Therefore, annotate the code with some "allow dead code" to make linters
pass...