cli: Improve error message if manifest is missing
Before:

$ chisel dev
Error: while reading Chisel.toml

Caused by:
    No such file or directory (os error 2)

After:

$ chisel dev
Error: Could not find `Chisel.toml` in `/Users/penberg/src/chiselstrike/chiselstrike`. Did you forget to run `chisel init` to initialize the project?

Fixes #539