build: Work around OpenSSL issue in newer Node
Without setting the `NODE_OPTIONS` to `--openssl-legacy-provider`,
the build fails for Node 18 with:

error: failed to run custom build command for `packages v0.13.0-dev.0 (chiselstrike/packages)`

Caused by:
  process didn't exit successfully: `chiselstrike/target/debug/build/packages-199dc2cd0c8bc6a3/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=./chiselstrike-api/package.json
  cargo:rerun-if-changed=./create-chiselstrike-app/index.ts
  cargo:rerun-if-changed=./create-chiselstrike-app/template/Chisel.toml
  cargo:rerun-if-changed=./create-chiselstrike-app/template/hello.ts
  cargo:rerun-if-changed=./create-chiselstrike-app/template/package.json
  cargo:rerun-if-changed=./create-chiselstrike-app/template/settings.json
  cargo:rerun-if-changed=./create-chiselstrike-app/template/tsconfig.json
  cargo:rerun-if-changed=./create-chiselstrike-app/tsconfig.json
  cargo:rerun-if-changed=./create-chiselstrike-app/package.json

  > create-chiselstrike-app@0.13.0-dev.0 prepare
  > npm run build

  > create-chiselstrike-app@0.13.0-dev.0 build
  > rimraf ./dist && ncc build ./index.ts -o ./dist/

  ncc: Version 0.33.1
  ncc: Compiling file index.js into CJS

  --- stderr
  Error: error:0308010C:digital envelope routines::unsupported
      at new Hash (node:internal/crypto/hash:67:19)
      at Object.createHash (node:crypto:133:10)
      at hashOf (chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1890023)
      at ncc (chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1894690)
      at runCmd (chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:52268)
      at 819 (chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:48838)
      at __webpack_require__ (chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59076)
      at chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59288
      at chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59349
      at Object.<anonymous> (chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/cli.js:8:28) {
    opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
    library: 'digital envelope routines',
    reason: 'unsupported',
    code: 'ERR_OSSL_EVP_UNSUPPORTED'
  }
  npm ERR! code 1
  npm ERR! path work/chiselstrike/packages/create-chiselstrike-app
  npm ERR! command failed
  npm ERR! command sh -c npm run build

  npm ERR! A complete log of this run can be found in:
  npm ERR!     .npm/_logs/2022-10-03T07_35_46_008Z-debug-0.log
  thread 'main' panicked at 'assertion failed: status.unwrap().success()', packages/build.rs:67:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Signed-off-by: Piotr Jastrzebski <piotr@chiselstrike.com>