create-chiselstrike-app: Fix node version in package.json
If you attempt to `npx create-chiselstrike-app` with older versions of
Node, you see the following error:

Error: Cannot find module 'node:process'

The issue is that the following require syntax:

  const external_node_process_namespaceObject = require("node:process");

is only supported in Node 14.18 and later:

https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.18.0

Therefore, bump up the engine in `package.json` to reflect that.