create-chiselstrike-app: Depend on exact versions
Let's depend on exact versions instead of compatible versions to keep
builds reproducible.

The practical reason is that the current `typescript` dependency
installs latest 4.7.2, which fails the build:

ncc: Using typescript@4.7.2 (local user-provided)
Error: Module build failed (from ./node_modules/@vercel/ncc/dist/ncc/loaders/ts-loader.js):
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective (/Users/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/typescript/lib/typescript.js:42530:18)
    at /Users/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/loaders/ts-loader.js.cache.js:13:316837
    at /Users/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/loaders/ts-loader.js.cache.js:13:303785
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/Users/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/loaders/ts-loader.js.cache.js:13:303777)
    at actualResolveTypeReferenceDirectiveNamesWorker (/Users/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/typescript/lib/typescript.js:116611:163)
    at resolveTypeReferenceDirectiveNamesWorker (/Users/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/typescript/lib/typescript.js:116911:26)
    at processTypeReferenceDirectives (/Users/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/typescript/lib/typescript.js:118393:31)
    at findSourceFileWorker (/Users/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/typescript/lib/typescript.js:118278:21)
    at findSourceFile (/Users/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/typescript/lib/typescript.js:118133:26)
    at /Users/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1770552
    at /Users/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:374702
    at _done (eval at create (/Users/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:20:75523), <anonymous>:9:1)
    at eval (eval at create (/Users/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:20:75523), <anonymous>:34:22)

As it's still an open issue, we anyway need to avoid that specific
version:

https://github.com/microsoft/TypeScript/issues/49257

But better to just have explicit version numbers to avoid stuff breaking
when our source stays the same.

(cherry picked from commit c2f474806efc791a317e4b425e880fe3a1e3b741)