Add 'chiselstrike-cli' package
This adds a 'chiselstrike-cli' package, which includes just the
ChiselStrike binaries. The 'chiselstrike' package is now just the
ChiselStrike API.

The upside is that now CLI packaging is easier to reason about, which
makes it easier to fix a packaging bug where "getBinary.js" was left ouf
the package, causing the following issue when attempting to run "chisel
dev" from package.json scripts:

% npm run dev

> hello@1.0.0 dev
> chisel dev

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './getBinary'
Require stack:
- /Users/penberg/src/chiselstrike/chiselstrike/packages/create-chisel-app/foo/node_modules/@chiselstrike/chiselstrike/npm/run.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/penberg/src/chiselstrike/chiselstrike/packages/create-chisel-app/foo/node_modules/@chiselstrike/chiselstrike/npm/run.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/penberg/src/chiselstrike/chiselstrike/packages/create-chisel-app/foo/node_modules/@chiselstrike/chiselstrike/npm/run.js'
  ]
}