chisel: Improve error message if manifest parsing fails
Before:

$ chisel dev
Error: missing field `models` at line 1 column 1

After:

$ chisel dev
Error: Failed to parse manifest at `/Users/penberg/src/chiselstrike/chiselstrike/foo/Chisel.toml`:

missing field `models` at line 1 column 1