cli: Improve UX if manifest-specified directories don't exists
Before:

🙇‍♂️ Thank you for your interest in the ChiselStrike private beta! (Beta-Jan22.2)
⚠️  This is provided to you for evaluation purposes and should not be used to host production at this time
Docs with a description of expected functionality and command references at https://docs.chiselstrike.com
For any question, concerns, or early feedback, contact us at beta@chiselstrike.com

 🍾 We hope you have a great 2022! 🥂

INFO - ChiselStrike is ready 🚀 - URL: http://127.0.0.1:8080
Could not open modelsx

Caused by:
    No such file or directory (os error 2)
Error: No path was found. about ["modelsx"]

After:

$ chisel dev
Error: Manifest at `/Users/penberg/src/chiselstrike/chiselstrike/foo/Chisel.toml` has models directory `/Users/penberg/src/chiselstrike/chiselstrike/foo/modelsx` that does not exist.