create-chiselstrike-app: More human-friendly error message on Windows
Instead of showing a stack trace from failure to install
`@chiselstrike/cli` package, let's show the following error message
instead:

Error: Failed to create a ChiselStrike project.

ChiselStrike is currently supported on Windows through Windows Subsystem for Linux (WSL).

Please create your project in an ext4 filesystem (like the $HOME folder) to support hot reloading of endpoints.

For more information, see the documentation at: https://docs.chiselstrike.com

Fixes #1125