cli: Fix Tokio dependency features
If you build the "cli" project separately with:

  cd cli && cargo build

or run the "scripts/cargo-install" script, build fails as follows:

  error: The default runtime flavor is `multi_thread`, but the `rt-multi-thread` feature is disabled.
     --> cli/src/main.rs:342:1
      |
  342 | #[tokio::main]
      | ^^^^^^^^^^^^^^
      |
      = note: this error originates in the attribute macro `tokio::main` (in Nightly builds, run with -Z macro-backtrace for more info)

  error: could not compile `cli` due to previous error

Note that for some reason, the top-level "cargo build" that builds the
*workspace* does not trigger this issue, which suggest we need to
consider changing the CI steps to catch these issues.