tests: Add test case for findOne() filter splitting
Fails as follows without commit 7c02fac2 ("chiselc: Fix filter splitting
for find{Many,One}"):

  2 |      Unhandled exception: Error: Promise rejected without a handler: TypeError: User.__findOne(...).filter is not a function
  3 |          at file:///worker.js:6:15
  4 |          at Object.default [as /dev/entity-methods] (file:///dev/entity-methods.js?ver=0:27:31)
  5 |          at callHandlerImpl (file:///worker.js:150:41)
  6 |          at async rollback_on_failure (file:///worker.js:65:16)
  7 |          at async handleMsg (file:///worker.js:21:17)
  8 |      Unhandled exception: Error: Promise rejected without a handler: Error: operation canceled
  9 |          at file:///worker.js:6:15
  10|          at Function.__findOne (file:///chisel.ts:413:26)