Skip the deno_checks test
Commit 69873f2d added a test that consistently fails on some machines
with the following error:

 thread 'main' panicked at 'called Result::unwrap() on an Err value:
 Unable to build http client: builder error: Unknown TLS backend
 passed to use_preconfigured_tls',
 /.../.cargo/registry/src/github.com-1ecc6299db9ec823/deno_fetch-0.50.0/lib.rs:103:10

Skip the test temporarily until we can diagnose it.

Signed-off-by: Dejan Mircevski <dejan@chiselstrike.com>