store information about which queries fail
It also reduces a lot of boilerplate, as an added benefit.

Before:

Error: fetch failed `error returned from database: syntax error at or near "WHERE"`

Caused by:
    0: error returned from database: syntax error at or near "WHERE"
    1: syntax error at or near "WHERE"

After:

Error: query SELECT types.type_id AS type_id, types.backing_table AS backing_table, type_names.name AS type_name FROM types INNER JOIN type_names WHERE types.type_id = type_names.type_id

Caused by:
    0: fetch failed `error returned from database: syntax error at or near "WHERE"`
    1: error returned from database: syntax error at or near "WHERE"
    2: syntax error at or near "WHERE"