improve error message in case modules can't be resolved.
Right now if we fail to compile code, we call unwrap(). That's not
ideal, as we'd like to return more gracefully. However, that's not
enough since even that, will just return a cryptic error message.

To improve the situation, in places that we know are likely to fail
due to user error (like module resolution, where the user can just
refer to an non existing file), we'll do better by capturing the error
into diagnostics and adding helpful context.

Before:

```
deno:core/01_core.js:4083: Uncaught Error: No such file or directory (os error 2)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', tsc_compile/src/lib.rs:240:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After:

```
Error: parsing endpoint /dev/writer

Caused by:
    Compilation failed:
    Resolving ../models/models.js from /Users/glauber/pekka3/endpoints/writer.ts

    Caused by:
        No such file or directory (os error 2)
```